### PR TITLE
Re-pointing to a new site with Pantheon

### PR DESCRIPTION
**Pull request by yana-edt**
MSPGA-360
There is no need of S3 and CloudFronts with this re-point

### CODE REVIEW

**Comment by lizelliott** [comment]
@yana-edt all set on my side. I did **not** do a code review, just giving you stakeholder approval.

**Comment by yana-edt** [comment]
I removed those conditions now

**Comment by sprink** [comment]
would wait until Liz gives the greenlight before deploying

**Comment by lizelliott** [comment]
"www" isn't resolving yet. We can take a look in the morning.

**Comment by lizelliott** [comment]
Works now. All good.

**Pull request merged**
